#!/usr/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 8
bspc config top_padding 36

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#282828"
bspc config focused_border_color "#585858"

xrandr --output Virtual-1 --mode 1920x1080
xsetroot -solid '#383838'
xsetroot -cursor_name left_ptr
polybar topbar &
