font=JetBrainsMono Nerd Font Mono:size=13:style=Medium
prompt=" "

# anchor=center
# x-margin=0
# y-margin=0
# lines=15
# minimal-lines=no
# width=30
# tabs=8
# horizontal-pad=40
# vertical-pad=8
# inner-pad=0

[colors]
background=141415ff
text=cdcdcdff
message=cdcdcdff
prompt=cdcdcdff
placeholder=93a1a1ff
input=cdcdcdff
match=bb9dbdff
selection=bb9dbdff
selection-text=141415ff
selection-match=141415ff
counter=93a1a1ff
border=7e98e8ff

[border]
width=2
radius=0
