# Video
vo=gpu-next
gpu-api=vulkan
hwdec=vulkan-copy

# Scaling
scale=ewa_lanczos4sharpest
cscale=ewa_lanczos4sharpest
dscale=ewa_lanczos4sharpest

# Interpolation
blend-subtitles=yes
video-sync=display-resample
interpolation=yes
tscale=oversample

# Audio
volume=50
volume-max=200

# Language
alang=en, eng, english
slang=en, eng, english

# Screenshots
screenshot-format=png
screenshot-png-compression=1
screenshot-template=~/Pictures/%F - %p

# Misc
save-position-on-quit

# Protocols
[protocol.http]
hls-bitrate=max
cache=yes
no-cache-pause
[protocol.https]
profile=protocol.http
[protocol.ytdl]
profile=protocol.http
