# Video
profile=gpu-hq
gpu-api=vulkan

# Scaling
scale=ewa_lanczossharp
cscale=ewa_lanczossoft

# Interpolation
blend-subtitles=yes
video-sync=display-resample
interpolation=yes
tscale=oversample

# Hardware Decoding
hwdec=yes

# Audio
volume=80
volume-max=200

# Language
alang=en, eng, english
slang=en, eng, english

# Screenshots
screenshot-format=png
screenshot-png-compression=1
screenshot-template=~/Pictures/%F - %p

# Misc
ytdl=yes
ytdl-format="bestvideo+bestaudio/best"
save-position-on-quit
