# Video
vo=gpu-next
gpu-api=vulkan
hwdec=no

# Scaling
scale=ewa_lanczos
dscale=ewa_lanczos
cscale=ewa_lanczos

# Interpolation
blend-subtitles=yes
video-sync=display-resample
interpolation=yes
tscale=oversample

# Audio
volume=50
volume-max=200

# Language
alang=en, eng, english
slang=en, eng, english

# Screenshots
screenshot-format=png
screenshot-png-compression=1
screenshot-template=~/Pictures/%F - %p

# Misc
ytdl=yes
ytdl-format="bestvideo+bestaudio/best"
save-position-on-quit
