# Video
profile=gpu-hq
gpu-api=vulkan

# Scaling
scale=ewa_lanczossharp
dscale=mitchell
cscale=ewa_lanczossoft

# Interpolation
blend-subtitles=yes
video-sync=display-resample
interpolation=yes
tscale=box
tscale-window=sphinx
tscale-radius=1.0
tscale-clamp=0.0

# Hardware decoding
hwdec=auto-copy
hwdec-codecs=all

# Audio
volume=50
volume-max=200

# Language
alang=en, eng, english
slang=en, eng, english

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-template=~/Pictures/%F - %p

# Misc
ytdl=yes
ytdl-format="bestvideo+bestaudio/best"
save-position-on-quit
