#!/bin/bash

IFS=$'\\n'
for picture in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
    if file -i "$picture" | grep -q image; then
        jpg_file=`echo \"$picture\" | sed 's/\\.\\w*$/.jpg/'`
        /usr/bin/convert \"$picture\" jpeg:\"$jpg_file\"
        notify-send "Conversion complete" "The file $picture has been converted to JPEG format."
    else
        notify-send "Error" "The selected file is not an image file."
    fi
done
