#!/bin/bash

IFS=$'\\n'
for picture in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
    if file -i "$picture" | grep -q image; then
        png_file=`echo \"$picture\" | sed 's/\\.\\w*$/.png/'`
        /usr/bin/convert \"$picture\" png:\"$png_file\"
        notify-send "Conversion complete" "The file $picture has been converted to PNG format."
    else
        notify-send "Error" "The selected file is not an image file."
    fi
done
