#!/bin/bash

IFS=$'\\n'
for video in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
    if file -i "$video" | grep -q video; then
        gif_file=`echo \"$video\" | sed 's/\\.\\w*$/.gif/'`
        png_palette=`echo \"$video\" | sed 's/\\.\\w*$/.png/'`
        /usr/bin/ffmpeg -y -i \"$video\" -vf fps=15,scale=320:-1:flags=lanczos,palettegen \"$png_palette\"
        /usr/bin/ffmpeg -i \"$video\" -i \"$png_palette\" -filter_complex \"fps=15,scale=320:-1:flags=lanczos[x];[x][1:v]paletteuse\" \"$gif_file\"
        notify-send "Conversion complete" "The file $video has been converted to GIF format."
    else
        notify-send "Error" "The selected file is not a video file."
    fi
done
