#!/bin/bash

API_KEY="YOUR_API_KEY_HERE"

for FILE in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do
  if file --mime-type "$FILE" | grep -q image; then
    RESPONSE=$(curl -s -H "Authorization: Client-ID $API_KEY" -F "image=@$FILE" https://api.imgur.com/3/image)
    LINK=$(echo $RESPONSE | jq -r '.data.link')
    xdg-open "$LINK"
    echo -n "$LINK" | xclip -selection clipboard
    notify-send "Image uploaded to Imgur" "$LINK"
  else
    notify-send "Invalid file type" "$FILE is not an image"
  fi
done
